### ISSUE TITLE
Grim1312 i am the real scammer don't copy my profile

### ISSUE THREAD

**Issue by Grim1312** [Grim1321/DCRAT-MODDED#1]
Please dont copy my profile.
no one cares about my garbages,i just can't code anything..and i crack software from other devs and sell them as my own source.To lazy to work or maybe to High.I want people to thing that i am hunting scammers but the reality is ,i am the scammer.I sell all the sources i have cracked to idiots,because they believe me.
Last time i have sell to one guy a source protector that i found on github,and it was not even working.
My Github has been banned because they found out that i am just a scammer.But i am back!My plan is to blackmail devs to release source and make them pay to me,if they not do so i release or sell the code sources.This is my dirty secret!
I am a honest thief.I will soon make new github to blackmail more people.
I will also post here some picture of clients that fall into my trap.
All that coming soon!

**Comment by Grim1321** [comment]
Arrogance is a sin and is punished.
